# Generated by Django 5.2.17 on 2026-08-28 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departement", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemandeTirage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matiere", models.CharField(max_length=100)),
                ("titre_epreuve", models.CharField(max_length=200)),
                ("nombre_exemplaires", models.PositiveIntegerField()),
                ("nombre_pages", models.PositiveIntegerField()),
                ("fichier_pdf", models.FileField(upload_to="epreuves_pdf/")),
                ("filiere", models.CharField(max_length=100)),
                ("niveau", models.CharField(max_length=50)),
                ("date_reservation", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("duree_minutes", models.PositiveIntegerField(default=15)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours d impression"),
                            ("TERMINE", "Terminé"),
                            ("REFUSE", "Refusé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.enseignant",
                    ),
                ),
            ],
        ),
    ]
